### ISSUE TITLE
챕터 4 오탈자 문의

### ISSUE THREAD

**Issue by JangIn-40** [sqlmvp/doitmysql#1]
안녕하세요 저자님! 책 잘 읽고 있습니다.
다름이 아니라 몇가지 제가 생각하는 오탈자에 대해서 문의를 드리고자 합니다.
챕터 4 125p 첫번째 실습 코드 실행결과와 두번째 실습 코드 실행결과가 같아야 하지 않을까 싶습니다.
챕터 4 127p 5.의 두번째줄 공백은 ' '으로 표현한다.에서 ' '가 꼭 스페이스를 입력한 것 같아 ''가 되어야 할 것 같습니다.
챕터 4 150p 첫번째 실습 코드 첫번째줄에서 SELECT special_features, rating, FROM film이라 되있는데 rating뒤에 콤마가 오면 안될 것 같습니다.
감사합니다!

**Comment by sqlmvp** [comment]
챕터 4 125p 첫번째 실습 코드 실행결과와 두번째 실습 코드 실행결과가 같아야 하지 않을까 싶습니다.
-> 결과 그림이 잘못 첨부되었네요.

챕터 4 127p 5.의 두번째줄 공백은 ' '으로 표현한다.에서 ' '가 꼭 스페이스를 입력한 것 같아 ''가 되어야 할 것 같습니다.
-> 네, 스페이스가 들어간것처럼 보일수도 있겠네요. 스페이스 없이 싱글 쿼테이션 입니다.

챕터 4 150p 첫번째 실습 코드 첫번째줄에서 SELECT special_features, rating, FROM film이라 되있는데 rating뒤에 콤마가 오면 안될 것 같습니다.
-> 네, 콤마가 없어야 정상입니다. 오타 입니다.

피드백 감사합니다.
